version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: prod
    ports:
      - "8001:8001"
      - "5678:5678"
    volumes:
      - .:/usr/src/app
    environment:
      FLASK_DEBUG: "true"

  redis:
    image: "redis:alpine"


